### ISSUE TITLE
Surveyor 0.6.10 with Surveystones breaks Fabric Waystones

### ISSUE THREAD

**Issue by murphy-slaw** [sleepingdragoninn/surveyor#35]
Surveyor 0.6.10+1.20
Surveystones 1.3.0+1.20
Fabric Waystones 3.3.2mc1.20.1
Minecraft 1.20.1

When right-clicking a waystone, the waystone reports as "discovered" but does not activate, and there is a Surveyor stack trace in the log related to a packet handling failure:

```
[20:28:15] [Server thread/ERROR] (Minecraft) Failed to handle packet net.minecraft.class_2885@127e7e74, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3222.method_5682()" because "player" is null
	at folk.sisby.surveyor.Surveyor.getUuid(Surveyor.java:87) ~[surveyor-0.6.10+1.20.jar:?]
	at folk.sisby.surveyor.packet.S2CPacket.send(S2CPacket.java:44) ~[surveyor-0.6.10+1.20.jar:?]
	at folk.sisby.surveyor.packet.SyncPacket.send(SyncPacket.java:12) ~[surveyor-0.6.10+1.20.jar:?]
	at folk.sisby.surveyor.landmark.WorldLandmarks.handleChanged(WorldLandmarks.java:105) ~[surveyor-0.6.10+1.20.jar:?]
	at folk.sisby.surveyor.landmark.WorldLandmarks.put(WorldLandmarks.java:128) ~[surveyor-0.6.10+1.20.jar:?]
	at folk.sisby.surveystones.FwaystoneEvents.discoverWaystone(FwaystoneEvents.java:26) ~[surveystones-1.3.0+1.20.jar:?]
	at wraith.fwaystones.integration.event.WaystoneEvents.lambda$static$0(WaystoneEvents.java:16) ~[wraith-waystones-3.3.2+mc1.20.1.jar:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at wraith.fwaystones.integration.event.WaystoneEvents.lambda$static$1(WaystoneEvents.java:16) ~[wraith-waystones-3.3.2+mc1.20.1.jar:?]
	at net.minecraft.class_1657.fabricWaystones$discoverWaystone(class_1657.java:11956) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.fabricWaystones$discoverWaystone(class_1657.java:11951) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.fabricWaystones$discoverWaystone(class_1657.java:11946) ~[client-intermediary.jar:?]
	at wraith.fwaystones.block.WaystoneBlock.method_9534(WaystoneBlock.java:314) ~[wraith-waystones-3.3.2+mc1.20.1.jar:?]
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_14262(class_3225.java:343) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12046(class_3244.java:1140) ~[client-intermediary.jar:?]
	at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[20:28:15] [Render thread/INFO] (Minecraft) [System] [CHAT] §6【Xocaqabi§6】§3has been discovered!
```

**Comment by sleepingdragoninn** [comment]
minor typo on our end, fixed in surveyor 0.6.11
