### ISSUE TITLE
Payload limit exceeded

### ISSUE THREAD

**Issue by Cynthia7979** [sleepingdragoninn/surveyor#57]
![Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes](https://github.com/user-attachments/assets/96c2a61d-6e94-4dc7-8858-ee9f0c76d433)
_Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes_

When Surveyor's chunk data for a server reaches a certain threshold, one or more of the packets it sends to the server exceeds the payload size limit of 32 KiB, causing the player to disconnect immediately after joining a server.

A workaround we found is to delete several arbitrary chunk files in `data/surveyor/<serverID>/minecraft/<dimension>`. Deleting the whole folder works as well.

Haven't looked at the code yet but what I suspect is happening is that, upon entering the server or a new dimension, Surveyor sends a single big packet containing a summary of which chunks it has on the client side. This would explain why the invalid payload appears only after having explored a large portion of the map.

## Context
Me and a few of my friends are playing on a modded server that hosts a very large RPG map called Drehmal: Apotheosis. As we progressed through the map, an increasing number of players reported getting the error "Payload may not be larger than 32767 bytes" and being kicked immediately upon joining the server, similar to the behavior of a chunkban or bookban.

Apart from the error message shown in the screenshot above, nothing in the logs were remotely relevant to the issue. I was unable to reproduce the issue using the same player `.dat` file on a local save. To see if anything in the map accidentally caused a bookban situation, I checked the following files using an NBT viewer, but none of them turned out to have an abnormal size or corrupted content:
- Region `.mca` file of the region the player's supposed to be in
- Entity data `.mca` file of the region the player's supposed to be in
- Player `.dat` file

We then found that if the player reinstalls the modpack, dumping all stored mod data in the process, then they will get to play again with no issue. I soon ran into the same problem and did some testing myself, and learned that:
1. The issue disappears when Surveyor is disabled (using the disable mod feature in Modrinth App)
2. Re-downloading Minecraft and mods, without resetting mod data, does not do anything
3. If I delete a few files in `data/surveyor/../minecraft/<dimension I'm in>`, then the issue fixes itself without needing a full reinstallation.

There were some 250+ files in said folder, the sizes of which ranging from 4 KiB to 434 KiB. I prioritized deleting the larger ones, but it seems like deleting any arbitrary few would have done the same.

## Specs
- **Minecraft**: 1.20.1
- **Mod loader**: Fabric 0.16.7
- **Launcher**: Modrinth App
- **Surveyor**: 0.6.23+
- **Surveystones**: 1.3.1
- **Antique Atlas 4**: 2.9.17+
- **Wraith Waystones (Fabric Waystones/fwaystones)**: 3.3.2

Can provide list of other mods on client/server if requested.

## Related Issues
#17 - We didn't use `/surveyor share` but the workaround seems similar.
#23 - Also encountered the up-to-a-minute loading time when connecting to a server. The loading time goes away completely if Surveyor (and Atlas) is disabled. Loading time also seems to be related to portion of map explored.
#25 - Similar "crash/disconnect as soon as entering world" behavior. We don't have any structure mod installed, and the map was originally generated and built in Vanilla, so the cause is probably not the same.

**Comment by sleepingdragoninn** [comment]
So the big question is "what packet is it" - most packets we expect to be large are built to split when they're too large, and provide a clear error when an atomic packet exceeds the size limit. If you provide a crash or latest.log via https://mclo.gs/ the stack trace might reveal which, otherwise I'll need your big surveyor data to test with.

**Comment by Cynthia7979** [comment]
This does not cause a crash (although the game does freeze for a short time when it sends the giant packet that will eventually be rejected by the server), so there's no crash log unfortunately.

I found a log one of our players shared when the bug first occurred, but it seems like the reason for server disconnect isn't logged: https://mclo.gs/xHAdw10

I'll go change my log4j configuration so it logs DEBUGs, and try reproducing the issue the next time I play on the map. If that still doesn't produce a verbose enough log at least I'll have the Surveyor data available 👍

**Comment by sleepingdragoninn** [comment]
thanks!

**Comment by AresWacky** [comment]
Ive been having this very issue and finally found myself here after looking into everything (pretty much everything Cynthia7979 said). We had been running our server for a few weeks and as more map became loaded more player instability. 

Using Antique Atlases 1.10.0, i had just noticed you updated a few days ago with the note: "Fix hanging on load with a large explored map area"

does this relate to this issue?

**Comment by sleepingdragoninn** [comment]
not at all, that's purely a client fix - still need to know what packet actually exceeded the limit here.

**Comment by XxInvictus** [comment]
I know it's not the full log, but this is an example of the error seen server-side, I have been able to narrow this down to a fine art of not having to have a player start fresh. The specific fix for players/operators that has worked for my server is to open the player's .dat file in `world/playerdata/{uuid}.dat` (using NBTExplorer) and removing the surveyor key and all it's child data.
```
[14:26:14] [Netty Epoll Server IO #1/ERROR] [ServerPlayNetworkAddon for *****/]: Encountered exception while handling in channel with name "surveyor:known_terrain"
java.lang.IndexOutOfBoundsException: Index 448 out of bounds for length 444
        at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?] {}
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?] {}
        at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?] {}
        at java.util.Objects.checkIndex(Unknown Source) ~[?:?] {re:mixin}
        at java.util.ArrayList.get(Unknown Source) ~[?:?] {re:mixin}
        at folk.sisby.surveyor.util.ListUtil.splitSet(ListUtil.java:12) ~[surveyor-0.6.26+1.20_mapped_srg_1.20.1.jar%231936!/:?] {re:classloading}
        at folk.sisby.surveyor.packet.S2CUpdateRegionPacket.toBufs(S2CUpdateRegionPacket.java:60) ~[surveyor-0.6.26+1.20_mapped_srg_1.20.1.jar%231936!/:?] {re:classloading}
        at folk.sisby.surveyor.packet.S2CUpdateRegionPacket.toBufs(S2CUpdateRegionPacket.java:60) ~[surveyor-0.6.26+1.20_mapped_srg_1.20.1.jar%231936!/:?] {re:classloading}
        at folk.sisby.surveyor.packet.S2CPacket.send(S2CPacket.java:21) ~[surveyor-0.6.26+1.20_mapped_srg_1.20.1.jar%231936!/:?] {re:classloading}
        at folk.sisby.surveyor.packet.S2CPacket.send(S2CPacket.java:27) ~[surveyor-0.6.26+1.20_mapped_srg_1.20.1.jar%231936!/:?] {re:classloading}
        at folk.sisby.surveyor.SurveyorNetworking.lambda$handleKnownTerrain$6(SurveyorNetworking.java:53) ~[surveyor-0.6.26+1.20_mapped_srg_1.20.1.jar%231936!/:?] {re:classloading}
        at java.util.HashMap.forEach(Unknown Source) ~[?:?] {re:mixin}
        at folk.sisby.surveyor.SurveyorNetworking.handleKnownTerrain(SurveyorNetworking.java:48) ~[surveyor-0.6.26+1.20_mapped_srg_1.20.1.jar%231936!/:?] {re:classloading}
        at folk.sisby.surveyor.SurveyorNetworking.handleServer(SurveyorNetworking.java:99) ~[surveyor-0.6.26+1.20_mapped_srg_1.20.1.jar%231936!/:?] {re:classloading}
        at folk.sisby.surveyor.SurveyorNetworking.lambda$init$1(SurveyorNetworking.java:37) ~[surveyor-0.6.26+1.20_mapped_srg_1.20.1.jar%231936!/:?] {re:classloading}
        at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:88) ~[fabric-networking-api-v1-1.3.14+fb7c822677.jar%231305!/:1.3.14+fb7c822677] {re:mixin,re:classloading}
        at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:40) ~[fabric-networking-api-v1-1.3.14+fb7c822677.jar%231305!/:1.3.14+fb7c822677] {re:mixin,re:classloading}
        at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) ~[fabric-networking-api-v1-1.3.14+fb7c822677.jar%231305!/:1.3.14+fb7c822677] {re:mixin,re:classloading}
        at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.handle(ServerPlayNetworkAddon.java:83) ~[fabric-networking-api-v1-1.3.14+fb7c822677.jar%231305!/:1.3.14+fb7c822677] {re:mixin,re:classloading}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handler$epn000$fabric_networking_api_v1$handleCustomPayloadReceivedAsync(ServerGamePacketListenerImpl.java:1844) ~[server-1.20.1-20230612.114412-srg.jar%231005!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-networking-api-v1.mixins.json:ServerPlayNetworkHandlerMixin from mod fabric_networking_api_v1,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.forge_vehicle_packets.ServerGamePacketListenerImplMixin from mod modernfix,pl:mixin:APP:logprot.mixins.json:ServerGamePacketListenerImplMixin from mod logprot,pl:mixin:APP:hardcorerevival.mixins.json:ServerGamePacketListenerImplMixin from mod hardcorerevival,pl:mixin:APP:mixins.artifacts.common.json:item.umbrella.server.ServerGamePacketListenerImplMixin from mod artifacts,pl:mixin:APP:mixins.vminus.json:server.ServerGamePacketListenerImplMixin from mod vminus,pl:mixin:APP:graveyard-common.mixins.json:ServerPlayNetworkHandlerMixin from mod graveyard,pl:mixin:APP:pehkui.mixins.json:ServerPlayNetworkHandlerMixin from mod pehkui,pl:mixin:APP:pehkui.mixins.json:compat1204minus.ServerPlayNetworkHandlerMixin from mod pehkui,pl:mixin:APP:pehkui.mixins.json:reach.compat1204minus.ServerPlayNetworkHandlerMixin from mod pehkui,pl:mixin:APP:pehkui.mixins.json:reach.compat1204minus.compat119plus.ServerPlayNetworkHandlerMixin from mod pehkui,pl:mixin:APP:neruina.mixins.json:catchers.ServerPlayNetworkHandlerMixin from mod neruina,pl:mixin:APP:bettercombat.mixins.json:ServerPlayNetworkHandlerMixin from mod bettercombat,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ServerPlayNetHandlerAccess from mod immersiveengineering,pl:mixin:APP:mixins/common/nochatreports.mixins.json:server.MixinServerGamePacketListenerImpl from mod nochatreports,pl:mixin:APP:aether.mixins.json:common.accessor.ServerGamePacketListenerImplAccessor from mod aether,pl:mixin:APP:railways.mixins.json:ServerGamePacketListenerImplMixin from mod railways,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.ServerGamePacketListenerImplMixin from mod the_bumblezone,pl:mixin:APP:the_bumblezone-common.mixins.json:gameplay.ServerGamePacketListenerImplAccessor from mod the_bumblezone,pl:mixin:APP:fabric-networking-api-v1.mixins.json:accessor.ServerPlayNetworkHandlerAccessor from mod fabric_networking_api_v1,pl:mixin:APP:endergetic.mixins.json:ServerGamePacketListenerImplMixin from mod endergetic,pl:mixin:APP:quark.mixins.json:accessor.AccessorServerGamePacketListener from mod quark,pl:mixin:APP:supplementaries-common.mixins.json:ServerGamePacketListenerMixin from mod supplementaries,pl:mixin:APP:packetfixer.v1_19_4.forge.mixins.json:v1_19_4_forge.ServerGamePacketListenerImplMixin from mod packetfixer,pl:mixin:APP:expandability-common.mixins.json:swimming.server.ServerGamePacketListenerImplMixin from mod expandability,pl:mixin:APP:mixins.dcintegration.json:MixinNetHandlerPlayServer from mod dcintegration,pl:mixin:A,pl:connector_pre_launch:A}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7423_(ServerGamePacketListenerImpl.java) ~[server-1.20.1-20230612.114412-srg.jar%231005!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-networking-api-v1.mixins.json:ServerPlayNetworkHandlerMixin from mod fabric_networking_api_v1,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.forge_vehicle_packets.ServerGamePacketListenerImplMixin from mod modernfix,pl:mixin:APP:logprot.mixins.json:ServerGamePacketListenerImplMixin from mod logprot,pl:mixin:APP:hardcorerevival.mixins.json:ServerGamePacketListenerImplMixin from mod hardcorerevival,pl:mixin:APP:mixins.artifacts.common.json:item.umbrella.server.ServerGamePacketListenerImplMixin from mod artifacts,pl:mixin:APP:mixins.vminus.json:server.ServerGamePacketListenerImplMixin from mod vminus,pl:mixin:APP:graveyard-common.mixins.json:ServerPlayNetworkHandlerMixin from mod graveyard,pl:mixin:APP:pehkui.mixins.json:ServerPlayNetworkHandlerMixin from mod pehkui,pl:mixin:APP:pehkui.mixins.json:compat1204minus.ServerPlayNetworkHandlerMixin from mod pehkui,pl:mixin:APP:pehkui.mixins.json:reach.compat1204minus.ServerPlayNetworkHandlerMixin from mod pehkui,pl:mixin:APP:pehkui.mixins.json:reach.compat1204minus.compat119plus.ServerPlayNetworkHandlerMixin from mod pehkui,pl:mixin:APP:neruina.mixins.json:catchers.ServerPlayNetworkHandlerMixin from mod neruina,pl:mixin:APP:bettercombat.mixins.json:ServerPlayNetworkHandlerMixin from mod bettercombat,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ServerPlayNetHandlerAccess from mod immersiveengineering,pl:mixin:APP:mixins/common/nochatreports.mixins.json:server.MixinServerGamePacketListenerImpl from mod nochatreports,pl:mixin:APP:aether.mixins.json:common.accessor.ServerGamePacketListenerImplAccessor from mod aether,pl:mixin:APP:railways.mixins.json:ServerGamePacketListenerImplMixin from mod railways,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.ServerGamePacketListenerImplMixin from mod the_bumblezone,pl:mixin:APP:the_bumblezone-common.mixins.json:gameplay.ServerGamePacketListenerImplAccessor from mod the_bumblezone,pl:mixin:APP:fabric-networking-api-v1.mixins.json:accessor.ServerPlayNetworkHandlerAccessor from mod fabric_networking_api_v1,pl:mixin:APP:endergetic.mixins.json:ServerGamePacketListenerImplMixin from mod endergetic,pl:mixin:APP:quark.mixins.json:accessor.AccessorServerGamePacketListener from mod quark,pl:mixin:APP:supplementaries-common.mixins.json:ServerGamePacketListenerMixin from mod supplementaries,pl:mixin:APP:packetfixer.v1_19_4.forge.mixins.json:v1_19_4_forge.ServerGamePacketListenerImplMixin from mod packetfixer,pl:mixin:APP:expandability-common.mixins.json:swimming.server.ServerGamePacketListenerImplMixin from mod expandability,pl:mixin:APP:mixins.dcintegration.json:MixinNetHandlerPlayServer from mod dcintegration,pl:mixin:A,pl:connector_pre_launch:A}
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:35) ~[server-1.20.1-20230612.114412-srg.jar%231005!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:fabric-networking-api-v1.mixins.json:accessor.CustomPayloadC2SPacketAccessor from mod fabric_networking_api_v1,pl:mixin:APP:packetfixer.v1_19_4.forge.mixins.json:v1_19_4_forge.ServerboundCustomPayloadPacketMixin from mod packetfixer,pl:mixin:A,pl:connector_pre_launch:A}
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%231005!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:fabric-networking-api-v1.mixins.json:accessor.CustomPayloadC2SPacketAccessor from mod fabric_networking_api_v1,pl:mixin:APP:packetfixer.v1_19_4.forge.mixins.json:v1_19_4_forge.ServerboundCustomPayloadPacketMixin from mod packetfixer,pl:mixin:A,pl:connector_pre_launch:A}
        at net.minecraft.network.Connection.m_129517_(Connection.java:174) ~[server-1.20.1-20230612.114412-srg.jar%231005!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A}
        at net.minecraft.network.Connection.channelRead0(Connection.java:159) ~[server-1.20.1-20230612.114412-srg.jar%231005!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A}
        at net.minecraft.network.Connection.channelRead0(Connection.java:50) ~[server-1.20.1-20230612.114412-srg.jar%231005!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A}
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {re:mixin,re:computing_frames}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar%2381!/:4.1.82.Final] {re:mixin}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar%2381!/:4.1.82.Final] {re:mixin}
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar%2381!/:4.1.82.Final] {re:mixin}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar%2381!/:4.1.82.Final] {re:mixin}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar%2381!/:4.1.82.Final] {re:mixin}
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[netty-codec-4.1.82.Final.jar%2381!/:4.1.82.Final] {re:mixin}
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444) ~[netty-codec-4.1.82.Final.jar%2381!/:4.1.82.Final] {re:mixin}
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-codec-4.1.82.Final.jar%2381!/:4.1.82.Final] {re:mixin}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar%2381!/:4.1.82.Final] {re:mixin}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.82.Final.jar%2383!/:4.1.82.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final] {}
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.82.Final.jar%2386!/:4.1.82.Final] {}
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[netty-transport-classes-epoll-4.1.82.Final.jar%2386!/:4.1.82.Final] {}
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[netty-transport-classes-epoll-4.1.82.Final.jar%2386!/:4.1.82.Final] {}
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar%2382!/:4.1.82.Final] {}
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar%2382!/:4.1.82.Final] {}
        at java.lang.Thread.run(Unknown Source) ~[?:?] {re:mixin}
```

**Comment by sleepingdragoninn** [comment]
above index error was fixed in 1.0, so going to close this as stale I think. still open to exact packet ID reports
